---
# Add EE to controller

- name: "Ensure the EEs are registered on the controller"
  ansible.controller.execution_environment:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: "{{ aap_validate_certs }}"
    name: "{{ ee.name }}"
    image: "{{ ee.image }}"
    pull: "{{ ee.pull | default(omit) }}"
    organization: "{{ ee.organization | default(omit) }}"
    description: "{{ ee.description | default(omit) }}"
    credential: "{{ ee.credential | default(omit) }}"
