---
- name: "Build Execution Environments"
  hosts: automation_hub
  remote_user: ansiblerunner
  become: true
  gather_facts: true
  vars_files:
    - "vars/common_vars.yml"
    - "vars/controller_vars.yml"
    - "vars/hub_vars.yml"
    - "vars/rhis_post_vars.yml"
    - "~/rhisbuilder_vault.yml"

  tasks:

    # Create the ee's and add them to the Hub and Controller
    - name: "Build Execution Environments"
      ansible.builtin.include_tasks: "rhis_post/tasks/build_ees.yml"

    - name: "Register Execution Environments"
      ansible.builtin.include_tasks: "rhis_post/tasks/add_ees.yml"
